title: 'sensenet Community'
email: snteam@sensenet.com
description: 'sensenet Community Website'
twitter:
    username: sensenet
facebook:
    facebook: sensenetcsp
github_username: SenseNet
author: SenseNet
future: true
excerpt_separator: '---'
plugins:
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-feed
    - jemoji
    - algoliasearch-jekyll
    - jekyll-sitemap
collections:
    updates: {output: true, permalink: '/updates/:year/:month/:day'}
    releases: {output: true, permalink: '/releases/:year/:month/:day'}
defaults:
    - {scope: {type: posts}, values: {layout: post, permalink: '/blog/:year/:month/:day/:title'}}
    - {scope: {type: updates}, values: {layout: update, permalink: '/updates/:year/:month/:day' }}
    - {scope: {type: releases}, values: {layout: release, permalink: '/releases/:year/:month/:day' }}
exclude:
    - node_modules
    - README.md
    - LICENSE.md
    - CNAME
    - Gemfile
    - Gemfile.lock
    - package.json
    - script
    - _docs
include:
    - _pages
    - _updates
    - _releases
twitter:
    username: sensenet
logo: '/img/sensenet-logo.png'
social:
    name: Sense/Net
    links:
        - https://twitter.com/sensenet
        - https://www.facebook.com/sensenetcsp
        - https://www.linkedin.com/company/sense-net-inc
        - https://plus.google.com/+Sensenet
        - https://github.com/SenseNet
        - http://stackoverflow.com/tags/sensenet/info
        - https://www.instagram.com/sensenetinside/
port: 4001
repository: SenseNet/sensenet.github.io
sass:
    sass_dir: _sass
    style: compressed
encoding: utf-8
plugins_dir: _plugins